[2025-02-02T22:39:22.974+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T22:39:22.990+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_ingestion.load_to_bigquery manual__2025-02-02T22:39:16.154204+00:00 [queued]>
[2025-02-02T22:39:22.999+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_ingestion.load_to_bigquery manual__2025-02-02T22:39:16.154204+00:00 [queued]>
[2025-02-02T22:39:23.000+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-02T22:39:23.013+0000] {taskinstance.py:2889} INFO - Executing <Task(GCSToBigQueryOperator): load_to_bigquery> on 2025-02-02 22:39:16.154204+00:00
[2025-02-02T22:39:23.022+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'batch_ingestion', 'load_to_bigquery', 'manual__2025-02-02T22:39:16.154204+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/batch_ingestion.py', '--cfg-path', '/tmp/tmp4wmeiq9p']
[2025-02-02T22:39:23.025+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask load_to_bigquery
[2025-02-02T22:39:23.025+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=203) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-02T22:39:23.026+0000] {standard_task_runner.py:72} INFO - Started process 205 to run task
[2025-02-02T22:39:23.065+0000] {task_command.py:467} INFO - Running <TaskInstance: batch_ingestion.load_to_bigquery manual__2025-02-02T22:39:16.154204+00:00 [running]> on host c6c7c90780af
[2025-02-02T22:39:23.132+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batch_ingestion' AIRFLOW_CTX_TASK_ID='load_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T22:39:16.154204+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-02T22:39:16.154204+00:00'
[2025-02-02T22:39:23.134+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T22:39:23.152+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-02-02T22:39:23.157+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-02-02T22:39:23.158+0000] {gcs_to_bigquery.py:389} INFO - Using existing BigQuery table for storing data...
[2025-02-02T22:39:23.192+0000] {gcs_to_bigquery.py:393} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'fit-analytics-pipeline', 'datasetId': 'fitness_data', 'tableId': 'fitness_metrics'}, 'sourceFormat': 'NEWLINE_DELIMITED_JSON', 'sourceUris': ['gs://fitness-data-bucket/batch_data/batch_fitness_data.json'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False}}
[2025-02-02T22:39:23.194+0000] {bigquery.py:1241} INFO - Inserting job ***_batch_ingestion_load_to_bigquery_2025_02_02T22_39_16_154204_00_00_f8efb07f956f6a1afe585ca0fc1b2365
[2025-02-02T22:39:25.197+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 458, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: Failed to parse JSON: No object found when new array is started.; BeginArray returned false; Parser terminated before end of string File: batch_fitness_data.json; reason: invalid, location: batch_fitness_data.json, message: Error while reading data, error message: Failed to parse JSON: No object found when new array is started.; BeginArray returned false; Parser terminated before end of string File: batch_fitness_data.json
[2025-02-02T22:39:25.214+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=batch_ingestion, task_id=load_to_bigquery, run_id=manual__2025-02-02T22:39:16.154204+00:00, execution_date=20250202T223916, start_date=20250202T223922, end_date=20250202T223925
[2025-02-02T22:39:25.231+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T22:39:25.232+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 39 for task load_to_bigquery (400 Error while reading data, error message: Failed to parse JSON: No object found when new array is started.; BeginArray returned false; Parser terminated before end of string File: batch_fitness_data.json; reason: invalid, location: batch_fitness_data.json, message: Error while reading data, error message: Failed to parse JSON: No object found when new array is started.; BeginArray returned false; Parser terminated before end of string File: batch_fitness_data.json; 205)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 458, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: Failed to parse JSON: No object found when new array is started.; BeginArray returned false; Parser terminated before end of string File: batch_fitness_data.json; reason: invalid, location: batch_fitness_data.json, message: Error while reading data, error message: Failed to parse JSON: No object found when new array is started.; BeginArray returned false; Parser terminated before end of string File: batch_fitness_data.json
[2025-02-02T22:39:25.251+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-02T22:39:25.270+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-02T22:39:25.272+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
