[2025-02-02T19:16:06.684+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T19:16:06.710+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_ingestion.upload_to_gcs manual__2025-02-02T18:58:47.133339+00:00 [queued]>
[2025-02-02T19:16:06.725+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_ingestion.upload_to_gcs manual__2025-02-02T18:58:47.133339+00:00 [queued]>
[2025-02-02T19:16:06.726+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-02-02T19:16:06.747+0000] {taskinstance.py:2889} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_to_gcs> on 2025-02-02 18:58:47.133339+00:00
[2025-02-02T19:16:06.765+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'batch_ingestion', 'upload_to_gcs', 'manual__2025-02-02T18:58:47.133339+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/batch_ingestion.py', '--cfg-path', '/tmp/tmp4v8xucyd']
[2025-02-02T19:16:06.769+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask upload_to_gcs
[2025-02-02T19:16:06.773+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=191) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-02T19:16:06.774+0000] {standard_task_runner.py:72} INFO - Started process 193 to run task
[2025-02-02T19:16:06.830+0000] {task_command.py:467} INFO - Running <TaskInstance: batch_ingestion.upload_to_gcs manual__2025-02-02T18:58:47.133339+00:00 [running]> on host aa531ec81fb8
[2025-02-02T19:16:07.168+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batch_ingestion' AIRFLOW_CTX_TASK_ID='upload_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T18:58:47.133339+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-02T18:58:47.133339+00:00'
[2025-02-02T19:16:07.169+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T19:16:07.209+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-02-02T19:16:07.210+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-02-02T19:16:07.211+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 102, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /tmp/batch_fitness_data.json
[2025-02-02T19:16:07.220+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=batch_ingestion, task_id=upload_to_gcs, run_id=manual__2025-02-02T18:58:47.133339+00:00, execution_date=20250202T185847, start_date=20250202T191606, end_date=20250202T191607
[2025-02-02T19:16:07.232+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T19:16:07.233+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task upload_to_gcs (/tmp/batch_fitness_data.json; 193)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 102, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /tmp/batch_fitness_data.json
[2025-02-02T19:16:07.273+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-02T19:16:07.291+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-02T19:16:07.296+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
