[2025-02-18T16:20:01.130+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T16:20:01.149+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run.run_dbt scheduled__2025-02-18T16:00:00+00:00 [queued]>
[2025-02-18T16:20:01.161+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run.run_dbt scheduled__2025-02-18T16:00:00+00:00 [queued]>
[2025-02-18T16:20:01.162+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-18T16:20:01.178+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt> on 2025-02-18 16:00:00+00:00
[2025-02-18T16:20:01.187+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_run', 'run_dbt', 'scheduled__2025-02-18T16:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run_dag.py', '--cfg-path', '/tmp/tmpswne0i68']
[2025-02-18T16:20:01.190+0000] {standard_task_runner.py:105} INFO - Job 34: Subtask run_dbt
[2025-02-18T16:20:01.195+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1361) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-18T16:20:01.196+0000] {standard_task_runner.py:72} INFO - Started process 1362 to run task
[2025-02-18T16:20:01.243+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_run.run_dbt scheduled__2025-02-18T16:00:00+00:00 [running]> on host eeda3fda8711
[2025-02-18T16:20:01.343+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-18T16:00:00+00:00'
[2025-02-18T16:20:01.344+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T16:20:01.367+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-18T16:20:01.369+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /fitness-data-pipeline/fitness_dbt && dbt run']
[2025-02-18T16:20:01.380+0000] {subprocess.py:99} INFO - Output:
[2025-02-18T16:20:03.410+0000] {subprocess.py:106} INFO - [0m16:20:03  Running with dbt=1.9.2
[2025-02-18T16:20:04.838+0000] {subprocess.py:106} INFO - [0m16:20:04  Registered adapter: bigquery=1.9.1
[2025-02-18T16:20:04.960+0000] {subprocess.py:106} INFO - [0m16:20:04  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-02-18T16:20:06.004+0000] {subprocess.py:106} INFO - [0m16:20:06  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-02-18T16:20:06.006+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-02-18T16:20:06.007+0000] {subprocess.py:106} INFO - - models.fitness_dbt
[2025-02-18T16:20:06.139+0000] {subprocess.py:106} INFO - [0m16:20:06  Found 491 macros
[2025-02-18T16:20:06.145+0000] {subprocess.py:106} INFO - [0m16:20:06  Nothing to do. Try checking your model configs and model specification args
[2025-02-18T16:20:07.451+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-18T16:20:07.481+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T16:20:07.482+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_run, task_id=run_dbt, run_id=scheduled__2025-02-18T16:00:00+00:00, execution_date=20250218T160000, start_date=20250218T162001, end_date=20250218T162007
[2025-02-18T16:20:07.525+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T16:20:07.540+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T16:20:07.543+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
